version: '3'
services:
  postgresql:
    container_name: 'postgres'
    image: postgres:16.4
    networks:
      - mynetwork
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./project/db:/var/lib/postgresql/data

  php:
    container_name: 'php'
    build:
      context: .
      dockerfile: Dockerfile
    image: php:0.9
    volumes:
      - ./project/app:/project/app # Монтируем код приложения
      - ./project/tests:/project/tests # Монтируем директорию с тестами
      # Монтируем файлы управления зависимостями
      - ./project/package.json:/project/package.json
      - ./project/package-lock.json:/project/package-lock.json
      - ./project/composer.json:/project/composer.json
      - ./project/composer.lock:/project/composer.lock
      # Монтируем конфигурационные файлы
      - ./project/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./project/eslint.config.mjs:/project/eslint.config.mjs
      - ./project/.htmlhintrc:/project/.htmlhintrc
      - ./project/.stylelintrc:/project/.stylelintrc
      - ./project/phpunit.xml:/project/phpunit.xml
      - ./project/phpstan.neon:/project/phpstan.neon
    extra_hosts:
      - 'host.docker.internal:host-gateway' # Для взаимодействия Xdebug с хостом
    depends_on:
      - postgresql
    networks:
      - mynetwork

  nginx:
    container_name: 'nginx'
    image: nginx:1.27.0
    ports:
      - "80:80"
    volumes:
      - ./project/app:/project/app # Nginx будет обслуживать файлы из этой директории
      - ./project/nginx.conf:/etc/nginx/conf.d/default.conf # Подключаем конфигурацию Nginx
    depends_on:
      - php
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge