version: '3'
services:
  postgresql:
    container_name: 'postgres'
    image: postgres:16.4
    networks:
      - mynetwork
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db:/var/lib/postgresql/data

  php:
    container_name: 'php'
    build:
      context: .
      dockerfile: Dockerfile
    image: php:0.9
    volumes:
      - ./app:/app # Монтируем в общий путь
    extra_hosts:
      - 'host.docker.internal:host-gateway' # Для взаимодействия Xdebug с хостом
    networks:
      - mynetwork

  nginx:
    container_name: 'nginx'
    image: nginx:1.27.0
    ports:
      - "80:80"
    volumes:
      - ./app:/app # Nginx будет обслуживать файлы из этой директории
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf # Подключаем конфигурацию Nginx
    depends_on:
      - php
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge