<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <title>
    <?= htmlspecialchars($title) ?>
  </title>
  <link rel="stylesheet" href="/styles/style.css">
</head>

<body>
  <nav>
    <?php include __DIR__ . '/nav/navigation.phtml'; ?>
  </nav>
  <main>
    <?= $content ?>
  </main>
</body>

</html>