<div class="container">
  <div class="card">
    <h2>Создание пользователя</h2>
    <form method="post" action="/users" enctype="multipart/form-data">
      <div class="form-group">
        <label for="username">Логин*</label>
        <input
          type="text"
          id="username"
          name="username"
          placeholder="3-20 символов"
          maxlength="20"
          required
          value="<?= htmlspecialchars($flash['login'][0] ?? '') ?>" />
      </div>
      <div class="form-group">
        <label for="profile_picture">Аватар (0 - 300 кБ jpg/jpeg/png)</label>
        <input type="file" id="profile_picture" name="profile_picture" accept="image/png, image/jpeg" />
      </div>
      <div class="form-group">
        <label for="email">Емайл*</label>
        <input
          type="email"
          id="email"
          name="email"
          maxlength="50"
          required
          value="<?= htmlspecialchars($flash['email'][0] ?? '') ?>" />
      </div>
      <div class="form-group">
        <label for="password">Пароль*</label>
        <input
          type="password"
          id="password"
          name="password"
          placeholder="8-20 символов"
          maxlength="20"
          required />
      </div>
      <div class="form-group">
        <label for="confirm-password">Подтверждение пароля*</label>
        <input
          type="password"
          id="confirm-password"
          name="confirm_password"
          placeholder="8-20 символов"
          maxlength="20"
          required />
      </div>
      <div class="form-group">
        <label for="role">Admin или user</label>
        <select id="role" name="role">
          <option value="user" <?= (isset($flash['role'][0]) && $flash['role'][0] === 'user') ? 'selected' : '' ?>>user</option>
          <option value="admin" <?= (isset($flash['role'][0]) && $flash['role'][0] === 'admin') ? 'selected' : '' ?>>admin</option>
        </select>
      </div>
      <div class="form-group">
        <label for="is_active">Разрешена активность?</label>
        <input type="checkbox" id="is_active" name="is_active" value="true" <?= (isset($flash['is_active'][0]) && $flash['is_active'][0] === 'true') ? 'checked' : '' ?>>
      </div>
      <button type="submit">Создать</button>
    </form>
  </div>
</div>