<div class="container">
  <h2>Изменение пользователя</h2>
  <form method="post" action="./../index.php" enctype="multipart/form-data">
  <input type="hidden" name="http_method" value="PUT">
    <div class="form-group">
      <label for="username">Логин</label>
      <input type="text" id="username" name="username" required>
    </div>
    <div class="form-group">
      <label for="profile_picture">Аватар</label>
      <input type="file" id="profile_picture" name="profile_picture" accept="image/png, image/jpeg" />
    </div>
    <div class="form-group">
      <label for="email">Емайл</label>
      <input type="email" id="email" name="email" required>
    </div>
    <div class="form-group">
      <label for="password">Пароль</label>
      <input type="password" id="password" name="password" required>
    </div>
    <div class="form-group">
      <label for="confirm-password">Подтверждение пароля</label>
      <input type="password" id="confirm-password" name="confirm_password" required>
    </div>
    <div class="form-group">
      <label for="role">Admin или user</label>
      <select id="role" name="role">
        <option value="user" selected>user</option>
        <option value="admin">admin</option>
      </select>
    </div>
    <div class="form-group">
      <label for="is_active">Разрешена активность?</label>
      <input type="checkbox" id="is_active" name="is_active" value="true" checked>
    </div>
    <button type="submit">Изменить</button>
  </form>
</div>