<div class="container">
  <h2>Пользователи</h2>
  <div>
    <div class="button-container">
      <button><a href="/users/new">Создать</a></button>
    </div>
    <table>
      <thead>
      <tr>
          <th>ID</th>
          <th>Profile picture</th>
          <th>Login</th>
          <th>Email</th>
          <th>Last login</th>
          <th>Is active</th>
          <th>Created at</th>
          <th>Role</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($users as $user) : ?>
          <tr>
            <td><?= $user['id'] ?? '' ?></td>
            <td><img src="<?= $user['profile_picture'] ?? '' ?>" alt=""></td>
            <td><a href="/users/<?= $user['id'] ?? '' ?>"><?= $user['login'] ?? '' ?></a></td>
            <td><?= $user['email'] ?? '' ?></td>
            <td><?= $user['last_login'] ?? '' ?></td>
            <td><?= $user['is_active'] ?? '' ?></td>
            <td><?= $user['created_at'] ?? '' ?></td>
            <td><?= $user['role'] ?? '' ?></td>
            <td class="actions-button-container">
              <button><a href="/users/<?= $user['id'] ?>/edit">Изменить</a></button>
              <button><a href="/users/<?= $user['id'] ?>/delete">Удалить</a></button>
            </td>
          </tr>
        <?php endforeach ?>
      </tbody>
    </table>
  </div>
</div>