<div class="container">
  <h2>Пользователи</h2>
  <div>
    <form action="/users" method="get" class="search-form">
      <div class="search-row">
        <input
          type="text"
          name="search_login"
          placeholder="Поиск по логину"
          value="<?= htmlspecialchars($_GET['search_login'] ?? '') ?>"
          maxlength="254">
        <input
          type="text"
          name="search_email"
          placeholder="Поиск по емайл"
          value="<?= htmlspecialchars($_GET['search_email'] ?? '') ?>"
          maxlength="254">
      </div>
      <div class="search-row">
        <label for="search_last_login">Дата последнего посещения:</label>
        <label for="search_created_at">Дата регистрации:</label>
      </div>
      <div class="search-row">
        <input
          type="date"
          id="search_last_login"
          name="search_last_login"
          value="<?= htmlspecialchars($_GET['search_last_login'] ?? '') ?>">
        <input
          type="date"
          id="search_created_at"
          name="search_created_at"
          value="<?= htmlspecialchars($_GET['search_created_at'] ?? '') ?>">
      </div>
      <div class="search-row">
        <label for="search_role">Роль:</label>
        <label for="search_is_active">Статус:</label>
      </div>
      <div class="search-row">
        <select name="search_role" id="search_role">
          <option value=""></option>
          <option value="user" <?= (isset($_GET['search_role']) && $_GET['search_role'] === 'user') ? 'selected' : '' ?>>user</option>
          <option value="admin" <?= (isset($_GET['search_role']) && $_GET['search_role'] === 'admin') ? 'selected' : '' ?>>admin</option>
        </select>
        <select name="search_is_active" id="search_is_active">
          <option value=""></option>
          <option value="true" <?= (isset($_GET['search_is_active']) && $_GET['search_is_active'] === 'true') ? 'selected' : '' ?>>активен</option>
          <option value="false" <?= (isset($_GET['search_is_active']) && $_GET['search_is_active'] === 'false') ? 'selected' : '' ?>>неактивен</option>
        </select>
      </div>
      <div class="search-row button-row">
        <button type="submit">Поиск</button>
      </div>
    </form>
  </div>
  <div>
    <div class="button-container">
      Всего записей: <?= $totalRecords ?>
      <button><a href="/users/new">Создать</a></button>
    </div>
    <div class="footnote">* нажмите на заголовок поля таблицы для сортировки по этому полю, на логин пользователя - для просмотра его профиля</div>
    <table>
      <thead>
        <tr>
          <th>
            <a href="?sort_field=id&sort_order=<?= ($_GET['sort_order'] ?? 'asc') === 'asc' ? 'desc' : 'asc' ?>">
              ИД <?= ($_GET['sort_field'] ?? '') === 'id' ? ($_GET['sort_order'] === 'asc' ? '↑' : '↓') : '' ?>
            </a>
          </th>
          <th>Аватар</th>
          <th>
            <a href="?sort_field=login&sort_order=<?= ($_GET['sort_order'] ?? 'asc') === 'asc' ? 'desc' : 'asc' ?>">
              Логин <?= ($_GET['sort_field'] ?? '') === 'login' ? ($_GET['sort_order'] === 'asc' ? '↑' : '↓') : '' ?>
            </a>
          </th>
          <th>
            <a href="?sort_field=email&sort_order=<?= ($_GET['sort_order'] ?? 'asc') === 'asc' ? 'desc' : 'asc' ?>">
              Емайл <?= ($_GET['sort_field'] ?? '') === 'email' ? ($_GET['sort_order'] === 'asc' ? '↑' : '↓') : '' ?>
            </a>
          </th>
          <th>
            <a href="?sort_field=last_login&sort_order=<?= ($_GET['sort_order'] ?? 'asc') === 'asc' ? 'desc' : 'asc' ?>">
              Последнее посещение <?= ($_GET['sort_field'] ?? '') === 'last_login' ? ($_GET['sort_order'] === 'asc' ? '↑' : '↓') : '' ?>
            </a>
          </th>
          <th>
            <a href="?sort_field=is_active&sort_order=<?= ($_GET['sort_order'] ?? 'asc') === 'asc' ? 'desc' : 'asc' ?>">
              Статус <?= ($_GET['sort_field'] ?? '') === 'is_active' ? ($_GET['sort_order'] === 'asc' ? '↑' : '↓') : '' ?>
            </a>
          </th>
          <th>
            <a href="?sort_field=created_at&sort_order=<?= ($_GET['sort_order'] ?? 'asc') === 'asc' ? 'desc' : 'asc' ?>">
              Зарегистрирован <?= ($_GET['sort_field'] ?? '') === 'created_at' ? ($_GET['sort_order'] === 'asc' ? '↑' : '↓') : '' ?>
            </a>
          </th>
          <th>
            <a href="?sort_field=role&sort_order=<?= ($_GET['sort_order'] ?? 'asc') === 'asc' ? 'desc' : 'asc' ?>">
              Роль <?= ($_GET['sort_field'] ?? '') === 'role' ? ($_GET['sort_order'] === 'asc' ? '↑' : '↓') : '' ?>
            </a>
          </th>
          <th>Действия</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($users as $user) : ?>
          <tr>
            <td><?= $user['id'] ?? '' ?></td>
            <td><img src="<?= $user['profile_picture'] ?? '' ?>" alt=""></td>
            <td><a href="/users/<?= $user['id'] ?? '' ?>"><?= $user['login'] ?? '' ?></a></td>
            <td><?= $user['email'] ?? '' ?></td>
            <td><?= $user['last_login'] ?? '' ?></td>
            <td><?= $user['is_active'] ? 'активен' : 'неактивен' ?></td>
            <td><?= $user['created_at'] ?? '' ?></td>
            <td><?= $user['role'] ?? '' ?></td>
            <td class="actions-button-container">
              <button><a href="/users/<?= $user['id'] ?>/edit">Изменить</a></button>
              <form action="/users/<?= $user['id'] ?>" method="post">
                <input type="hidden" name="http_method" value="DELETE">
                <button type="submit">Удалить</button>
                <input type="checkbox" name="delete_confirmation" id="delete_confirmation" value="true">
              </form>
            </td>
          </tr>
        <?php endforeach ?>
      </tbody>
    </table>
    <!-- Пагинация -->
    <div class="pagination-container">
      <div class="pagination">
        <?php if ($currentPage > 1): ?>
          <a href="?page=<?= $currentPage - 1 ?>">&lt;&lt;</a>
        <?php endif; ?>
        <span>Страница <?= $currentPage ?> из <?= $totalPages ?></span>
        <?php if ($currentPage < $totalPages): ?>
          <a href="?page=<?= $currentPage + 1 ?>">&gt;&gt;</a>
        <?php endif; ?>
      </div>
      <div class="records-per-page">
        <form action="/users" method="get" class="records-form">
          <label for="records_per_page">Записей:</label>
          <select name="records_per_page" id="records_per_page" onchange="this.form.submit()">
            <option value="5" <?= ($recordsPerPage == 5) ? 'selected' : '' ?>>5</option>
            <option value="10" <?= ($recordsPerPage == 10) ? 'selected' : '' ?>>10</option>
            <option value="20" <?= ($recordsPerPage == 20) ? 'selected' : '' ?>>20</option>
            <option value="50" <?= ($recordsPerPage == 50) ? 'selected' : '' ?>>50</option>
          </select>
        </form>
      </div>
    </div>
  </div>
</div>