<div class="container">
  <div class="card">
    <h2>Профиль пользователя</h2>
    <h3><?= htmlspecialchars($user['login']) ?></h3>
    <?php if (!empty($user['profile_picture'])): ?>
      <a href="<?= htmlspecialchars($user['profile_picture']) ?>">
        <img src="<?= htmlspecialchars($user['profile_picture']) ?? ''?>" alt="Аватар пользователя">
      </a>
    <?php endif; ?>
    <p>Email: <?= htmlspecialchars($user['email']) ?></p>
    <p>Роль: <?= $user['role'] ?></p>
    <p>Зарегистрирован: <?= $user['created_at'] ?></p>
    <p>Последнее посещение: <?= $user['last_login'] ?></p>
    <p>Статус: <?= $user['is_active'] ? 'Активен' : 'Неактивен' ?></p>
    <div class="horizontal-container">
      <button><a href="/users/<?= $user['id'] ?>/edit">Изменить</a></button>
      <?php if ($admin): ?>
        <form action="/users/<?= $user['id'] ?>" method="post">
          <input type="hidden" name="http_method" value="DELETE">
          <button type="submit">Удалить</button>
          <input type="checkbox" name="delete_confirmation" id="delete_confirmation" value="true">
        </form>
      <?php endif; ?>
    </div>
  </div>
</div>