<div class="card">
  <h2>Регистрация</h2>
  <form method="post" action="./../index.php">
    <div class="form-group">
      <label for="username">Логин</label>
      <input type="text" id="username" name="username" required>
    </div>
    <div class="form-group">
      <label for="email">Емайл</label>
      <input type="email" id="email" name="email" required>
    </div>
    <div class="form-group">
      <label for="password">Пароль</label>
      <input type="password" id="password" name="password" required>
    </div>
    <div class="form-group">
      <label for="confirm-password">Подтверждение пароля</label>
      <input type="password" id="confirm-password" name="confirm_password" required>
    </div>
    <div class="form-group">
      <label for="captcha">Капча</label>
      <img src="./../src/Captcha.php" alt="Капча">
      <input type="text" id="captcha" name="captcha_input" required>
    </div>
    <button type="submit">Зарегистрироваться</button>
  </form>
</div>